import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";

export const metadata: Metadata = {
  title: "ROLEX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-lightBackground dark:bg-darkBackground max-w-screen">
        <div className="overflow-x-hidden pb-20  max-w-screen px-6 lg:px-20 min-h-screen flex flex-col gap-y-10">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
